// src/components/Search/SearchBar.jsx
import React from "react";
import { AiOutlineSearch } from "react-icons/ai";

const SearchBar = ({ handleSearch }) => {
  return (
    <div className="relative">
      <div className="bg-slate-200 relative rounded-lg h-10 p-4 shadow-md flex items-center" data-testid="search-bar">
        <AiOutlineSearch className="text-primary cursor-pointer" />
        <input
          className="bg-transparent ring-gray-600 outline-none text-sm w-48 ml-2 py-2 text-black placeholder:text-gray-800"
          type="text"
          placeholder="Search..."
          onChange={(e) => handleSearch(e)}
          aria-label="Search products"
          data-testid="search-input"
        />
      </div>
    </div>
  );
};

export default SearchBar;

// src/components/SearchBar.vue
<template>
  <div
    class="flex items-center gap-2 bg-gray-100 dark:bg-obsidian-3 border border-gray-200 dark:border-obsidian-2 rounded-xl px-3 h-10 w-56 transition-colors focus-within:border-brand"
    data-testid="search-bar"
  >
    <span class="text-brand shrink-0">🔍</span>
    <input
      type="text"
      :value="modelValue"
      :placeholder="ui.t('search')"
      aria-label="Search products"
      data-testid="search-input"
      class="bg-transparent outline-none text-sm flex-1 text-obsidian dark:text-white placeholder:text-gray-400 dark:placeholder:text-gray-500"
      @input="$emit('update:modelValue', $event.target.value)"
    />
  </div>
</template>

<script setup>
import { useUiStore } from '../stores/uiStore'
defineProps({ modelValue: { type: String, default: '' } })
defineEmits(['update:modelValue'])
const ui = useUiStore()
</script>
